const { chromium } = require('playwright');
const assert = require('node:assert/strict');
(async () => {
    const base = process.env.TEST_BASE_URL;
    if (!base || !process.env.TEST_ISOLATED_DATABASE || !process.env.TEST_ADMIN_PASSWORD) throw Error('An isolated database and test admin are required.');
    const browser = await chromium.launch({ channel: 'msedge', headless: true });
    let passed = 0;
    const check = (value, label) => { assert.ok(value, label); passed++; };
    const contexts = [];
    const create = async () => { const context = await browser.newContext({ ignoreHTTPSErrors: true }); contexts.push(context); return { context, page: await context.newPage() }; };
    const visit = async (page, path) => { const response = await page.goto(base + path); check(response.status() < 400, `GET ${path}: ${response.status()}`); };
    const token = async page => page.locator('[name="__RequestVerificationToken"]').first().inputValue();
    const post = (context, path, form) => context.request.post(base + path, { form, maxRedirects: 0 });
    try {
        const candidate = await create();
        const page = candidate.page;
        const errors = [];
        page.on('pageerror', error => errors.push(error.message));
        await visit(page, '/resume-builder');
        await page.locator('#resume-name').fill('Asha Kumar');
        await page.locator('#resume-headline').fill('Graduate Software Engineer');
        await page.locator('#resume-email').fill('asha@example.invalid');
        await page.locator('#resume-education').fill('B.Tech Computer Science | Example College\n2022–2026 | CGPA 8.5');
        await page.locator('#resume-projects').fill('<script>alert(1)</script>\nBuilt a job dashboard using C# and SQL.');
        check(await page.locator('[data-preview="name"]').innerText() === 'Asha Kumar', 'Live resume name');
        check(await page.locator('[data-preview="projects"] script').count() === 0, 'Resume content rendered as plain text');
        check(await page.locator('[data-resume-section="experience"]').isHidden(), 'Blank resume sections hidden');
        await page.locator('#save-resume').click();
        await page.reload();
        check(await page.locator('#resume-name').inputValue() === '', 'No automatic exposure of a saved draft');
        await page.locator('#load-resume').click();
        check(await page.locator('#resume-name').inputValue() === 'Asha Kumar', 'Saved resume restored');
        await page.locator('#resume-projects').fill('Job dashboard | C#, SQL\n• Created a search interface for 200 listings.');
        await page.evaluate(() => window.scrollTo(0, 0));
        await page.screenshot({ path: 'artifacts/resume-desktop.png', fullPage: true });
        await page.emulateMedia({ media: 'print' });
        check(await page.locator('.resume-editor').isHidden(), 'Editor excluded from printed resume');
        check(await page.locator('#resume-preview').isVisible(), 'Resume printable');
        await page.pdf({ path: 'artifacts/resume-preview.pdf', preferCSSPageSize: true });
        await page.screenshot({ path: 'artifacts/resume-print.png', fullPage: true });
        await page.emulateMedia({ media: 'screen' });
        await page.evaluate(() => { window.print = () => { window.printRequested = true; }; });
        await page.locator('#resume-form button[type="submit"]').click();
        check(await page.evaluate(() => window.printRequested === true), 'Print button opens print workflow');
        page.once('dialog', dialog => dialog.accept());
        await page.locator('#clear-resume').click();
        check(await page.locator('#resume-name').inputValue() === '', 'Clear resets editor');
        check(await page.evaluate(() => localStorage.getItem('d2djobs.resume.v1') === null), 'Clear deletes saved draft');
        await visit(page, '/resume-builder/services');
        let csrf = await token(page);
        let response = await post(candidate.context, '/resume-builder/services', { __RequestVerificationToken: csrf, Name: 'Test Candidate', Email: 'candidate@example.invalid', Service: 'Invented service' });
        check(response.status() === 200 && (await response.text()).includes('Choose a service'), 'Unknown services rejected');
        response = await post(candidate.context, '/resume-builder/services', { __RequestVerificationToken: csrf, Name: 'Test Candidate', Email: 'candidate@example.invalid', Service: 'ATS Resume Review', Notes: 'Please review my graduate resume.', Status: 'Completed' });
        check(response.status() === 302, 'Resume service request submitted');
        const employer = await create();
        await visit(employer.page, '/employer/register');
        csrf = await token(employer.page);
        const password = 'Test-only-employer-Password!2026';
        response = await post(employer.context, '/employer/register', { __RequestVerificationToken: csrf, CompanyName: 'Example Hiring', Email: 'employer@example.invalid', Password: password, ConfirmPassword: password });
        check(response.status() === 302, 'Employer registration');
        check((await employer.context.cookies()).some(c => c.name === 'D2DJobs.Employer' && c.secure && c.httpOnly), 'Secure isolated employer cookie');
        await visit(employer.page, '/employer');
        response = await employer.context.request.get(base + '/Admin', { maxRedirects: 0 });
        check(response.status() === 302 && response.headers().location.includes('/Admin/Login'), 'Employer cannot access admin');
        response = await employer.context.request.get(base + '/admin/commerce', { maxRedirects: 0 });
        check(response.status() === 302, 'Employer cannot access commerce review queue');
        await visit(employer.page, '/employer/jobs/new');
        csrf = await token(employer.page);
        const date = new Date(); const today = date.toISOString().slice(0, 10); date.setDate(date.getDate() + 30); const end = date.toISOString().slice(0, 10);
        const job = { __RequestVerificationToken: csrf, Title: 'Graduate QA Engineer', Category: 'Freshers Jobs', Location: 'Chennai', Qualification: 'B.Tech', Experience: '0–1 years', Salary: '₹4–6 LPA', Description: 'Build and test software alongside our graduate engineering team.', ApplyLink: 'https://example.com/careers', StartDate: today, EndDate: end };
        response = await post(employer.context, '/employer/jobs/new', { ...job, ApplyLink: 'javascript:alert(1)' });
        check(response.status() === 200 && (await response.text()).includes('HTTPS application'), 'Unsafe application URL rejected');
        response = await post(employer.context, '/employer/jobs/new', { ...job, EndDate: '2000-01-01' });
        check(response.status() === 200 && (await response.text()).includes('End date must'), 'Invalid campaign dates rejected');
        response = await post(employer.context, '/employer/jobs/new', { ...job, EmployerAccountId: '99999', ReviewStatus: 'Approved', IsFeatured: 'true' });
        check(response.status() === 302, 'Job submitted');
        await visit(employer.page, '/employer');
        check((await employer.page.locator('.campaign-card').innerText()).includes('Pending review'), 'Approval cannot be supplied by employer');
        const id = await employer.page.locator('[data-campaign-id]').first().getAttribute('data-campaign-id');
        response = await candidate.context.request.get(base + '/?search=Graduate%20QA%20Engineer');
        check(!(await response.text()).includes('class="details-link"'), 'Pending job not publicly listed');
        response = await post(employer.context, `/employer/jobs/${id}/upgrade`, {});
        check(response.status() === 400, 'CSRF required for upgrade');
        csrf = await token(employer.page);
        response = await post(employer.context, `/employer/jobs/${id}/upgrade`, { __RequestVerificationToken: csrf });
        check(response.status() === 302, 'Featured upgrade request');
        const other = await create();
        await visit(other.page, '/employer/register');
        response = await post(other.context, '/employer/register', { __RequestVerificationToken: await token(other.page), CompanyName: 'Other Employer', Email: 'other@example.invalid', Password: password, ConfirmPassword: password });
        check(response.status() === 302, 'Second employer registration');
        response = await other.context.request.get(base + `/employer/jobs/${id}/edit`);
        check(response.status() === 404, 'Cross-account campaign read blocked');
        await visit(other.page, '/employer/jobs/new');
        const otherToken = await token(other.page);
        response = await post(other.context, `/employer/jobs/${id}/edit`, { ...job, __RequestVerificationToken: otherToken });
        check(response.status() === 404, 'Cross-account campaign update blocked');
        response = await post(other.context, `/employer/jobs/${id}/upgrade`, { __RequestVerificationToken: otherToken });
        check(response.status() === 404, 'Cross-account upgrade blocked');
        const admin = await create();
        await visit(admin.page, '/Admin/Login');
        response = await post(admin.context, '/Admin/Login', { __RequestVerificationToken: await token(admin.page), userName: process.env.TEST_ADMIN_USER, password: process.env.TEST_ADMIN_PASSWORD });
        check(response.status() === 302, 'Admin sign-in');
        await visit(admin.page, '/admin/commerce');
        check((await admin.page.locator('body').innerText()).includes('Test Candidate'), 'Service enquiry in admin queue');
        check((await admin.page.locator('article').last().innerText()).includes('New'), 'Request status protected from overposting');
        const requestPath = await admin.page.locator('form[action*="/resume-requests/"]').first().getAttribute('action');
        response = await post(admin.context, requestPath, { __RequestVerificationToken: await token(admin.page), status: 'Contacted' });
        check(response.status() === 302, 'Admin updates service request');
        await visit(admin.page, '/admin/commerce');
        check((await admin.page.locator('article').last().innerText()).includes('Contacted'), 'Service status persists');
        const review = async (decision) => {
            await visit(admin.page, '/admin/commerce');
            const card = admin.page.locator(`[data-campaign-id="${id}"]`);
            const rowVersion = await card.locator('[name="rowVersion"]').first().inputValue();
            const response = await post(admin.context, `/admin/commerce/campaigns/${id}/review`, { __RequestVerificationToken: await token(admin.page), rowVersion, decision, note: 'Reviewed official details.' });
            check(response.status() === 302, 'Admin campaign ' + decision);
        };
        await review('Approve');
        await visit(employer.page, '/employer');
        check((await employer.page.locator('.campaign-card').innerText()).includes('Live'), 'Approved campaign live');
        const details = await employer.page.getByRole('link', { name: 'View listing', exact: true }).getAttribute('href');
        await visit(page, details);
        const applyHref = await page.locator('a[href*="ApplyClick"]').first().getAttribute('href');
        response = await candidate.context.request.get(base + applyHref, { maxRedirects: 0 });
        check(response.status() === 302 && response.headers().location === job.ApplyLink, 'Public application redirect');
        await visit(employer.page, '/employer');
        check((await employer.page.locator('.tools-metrics').innerText()).includes('100.0%'), 'Real views and clicks reflected in CTR');
        await visit(admin.page, '/admin/commerce');
        let card = admin.page.locator(`[data-campaign-id="${id}"]`);
        response = await post(admin.context, `/admin/commerce/campaigns/${id}/upgrade`, { __RequestVerificationToken: await token(admin.page), rowVersion: await card.locator('[name="rowVersion"]').first().inputValue(), decision: 'Approved' });
        check(response.status() === 302, 'Admin activates featured');
        await visit(admin.page, '/admin/commerce');
        csrf = await token(admin.page);
        response = await post(admin.context, `/admin/commerce/campaigns/${id}/invoice`, { __RequestVerificationToken: csrf, Number: 'TEST-001', SellerDetails: 'Example Seller\nChennai', BillTo: 'Example Hiring', Description: 'Agreed featured campaign', Amount: '499.00' });
        check(response.status() === 302, 'Admin invoice creation');
        await visit(employer.page, '/employer');
        const invoiceUrl = await employer.page.locator('a[href^="/employer/invoices/"]').first().getAttribute('href');
        await visit(employer.page, invoiceUrl);
        check((await employer.page.locator('.invoice-sheet').innerText()).includes('499.00'), 'Invoice total visible to owner');
        response = await other.context.request.get(base + invoiceUrl);
        check(response.status() === 404, 'Cross-account invoice blocked');
        await visit(admin.page, '/admin/commerce');
        const paidPath = await admin.page.locator('form[action$="/paid"]').first().getAttribute('action');
        response = await post(admin.context, paidPath, { __RequestVerificationToken: await token(admin.page) });
        check(response.status() === 302, 'Admin payment confirmation');
        await visit(employer.page, invoiceUrl);
        check(await employer.page.locator('.tool-badge').innerText() === 'Paid', 'Paid invoice status');
        const editPath = `/employer/jobs/${id}/edit`;
        await visit(employer.page, editPath);
        csrf = await token(employer.page);
        const version = await employer.page.locator('[name="RowVersion"]').inputValue();
        response = await post(employer.context, editPath, { ...job, __RequestVerificationToken: csrf, RowVersion: version, Title: 'Updated Graduate QA Engineer' });
        check(response.status() === 302, 'Owner edits campaign');
        response = await candidate.context.request.get(base + details);
        check(response.status() === 404, 'Edited listing paused pending review');
        response = await post(employer.context, editPath, { ...job, __RequestVerificationToken: csrf, RowVersion: version, Title: 'Stale overwrite' });
        check(response.status() === 302, 'Stale update handled');
        await visit(employer.page, editPath);
        check(await employer.page.locator('[name="Title"]').inputValue() === 'Updated Graduate QA Engineer', 'Stale edit did not overwrite campaign');
        const tomorrow = new Date(); tomorrow.setDate(tomorrow.getDate() + 2);
        response = await post(employer.context, editPath, { ...job, __RequestVerificationToken: await token(employer.page), RowVersion: await employer.page.locator('[name="RowVersion"]').inputValue(), StartDate: tomorrow.toISOString().slice(0, 10) });
        check(response.status() === 302, 'Future campaign dates saved');
        await review('Approve');
        await visit(employer.page, '/employer');
        check((await employer.page.locator('.campaign-card').innerText()).includes('Scheduled'), 'Future campaign scheduled');
        response = await candidate.context.request.get(base + details);
        check(response.status() === 404, 'Scheduled listing hidden before start');
        response = await candidate.context.request.get(base + applyHref);
        check(response.status() === 404, 'Scheduled application link blocked');
        await employer.page.screenshot({ path: 'artifacts/employer-desktop.png', fullPage: true });
        for (const width of [320, 390, 768, 1440]) {
            for (const [p, paths] of [[page, ['/resume-builder', '/resume-builder/services', '/employer/login', '/employer/register']], [employer.page, ['/employer', editPath, invoiceUrl]], [admin.page, ['/admin/commerce']]]) {
                await p.setViewportSize({ width, height: 900 });
                for (const path of paths) { await visit(p, path); check(!await p.evaluate(() => document.documentElement.scrollWidth > innerWidth), `No overflow: ${path} at ${width}px`); }
            }
        }
        await page.setViewportSize({ width: 390, height: 844 }); await visit(page, '/resume-builder');
        await page.screenshot({ path: 'artifacts/resume-mobile.png', fullPage: true });
        await employer.page.setViewportSize({ width: 390, height: 844 }); await visit(employer.page, '/employer');
        await employer.page.screenshot({ path: 'artifacts/employer-mobile.png', fullPage: true });
        response = await post(employer.context, '/employer/logout', { __RequestVerificationToken: await token(employer.page) });
        check(response.status() === 302, 'Employer logout');
        response = await employer.context.request.get(base + '/employer', { maxRedirects: 0 });
        check(response.status() === 302 && response.headers().location.includes('/employer/login'), 'Dashboard protected after logout');
        await visit(employer.page, '/employer/login');
        response = await post(employer.context, '/employer/login', { __RequestVerificationToken: await token(employer.page), Email: 'EMPLOYER@example.invalid', Password: password });
        check(response.status() === 302, 'Employer can sign back in with case-insensitive email');
        await visit(employer.page, '/employer');
        check((await employer.page.locator('.campaign-card').innerText()).includes('Graduate QA Engineer'), 'Campaigns persist after sign-in');
        check(errors.length === 0, 'No resume JavaScript errors: ' + errors.join(', '));
        console.log(JSON.stringify({ result: 'PASS', assertions: passed, database: process.env.TEST_ISOLATED_DATABASE }));
    } finally { await browser.close(); }
})().catch(error => { console.error(error.stack); process.exitCode = 1; });
