namespace JobForFresher.Models;

public sealed record ResourceSection(string Heading, string Body);
public sealed record CareerResource(string Slug, string Title, string Summary, DateOnly Updated, IReadOnlyList<ResourceSection> Sections);

public static class CareerResources
{
    public static readonly IReadOnlyList<CareerResource> All =
    [
        new("prepare-fresher-software-interview", "How to prepare for a fresher software interview", "A practical preparation plan covering fundamentals, coding, projects, communication, and the final day.", new(2026, 9, 30),
        [
            new("Start with the role, not a random syllabus", "Read the job description and group its requirements into programming, computer-science fundamentals, tools, projects, and communication. Mark each item as confident, needs revision, or unfamiliar. Spend most of your time on the first two groups; trying to learn an entire new stack immediately before an interview usually produces shallow answers."),
            new("Make fundamentals explainable", "Revise one programming language deeply enough to discuss data types, control flow, functions, collections, error handling, and object-oriented ideas. For software roles, review data structures, basic algorithms, databases, operating systems, networking, and version control at the depth suggested by the role. Practise explaining why you chose an approach, not only typing a solution."),
            new("Turn projects into evidence", "Prepare a two-minute explanation for each relevant project: the problem, your contribution, the tools, one difficult decision, how you tested it, and what you would improve. Interviewers often learn more from honest trade-offs than from a long feature list. Open the project before the interview and make sure you can navigate the important code or design."),
            new("Run a realistic final rehearsal", "Practise solving a small problem while speaking your reasoning aloud. Prepare concise answers about yourself, why the role fits, a challenge you handled, and a time you learned something quickly. The day before, confirm the time, platform or venue, identification, resume, charger, and internet connection. Sleep and arrive early instead of attempting an all-night revision session.")
        ]),
        new("write-fresher-resume", "How to write a fresher resume that is easy to verify", "Build a concise, truthful resume that makes education, skills, projects, and evidence easy to scan.", new(2026, 9, 30),
        [
            new("Give the first half-page a clear job", "Place your name, reliable contact details, education, strongest relevant skills, and best evidence near the top. A recruiter should quickly understand what kind of entry-level role you are prepared for. Avoid a generic objective that only says you want a challenging position; use that space for a short profile tied to real skills and work."),
            new("Describe projects with actions and outcomes", "For each project, state what you built, your own contribution, the tools used, and a measurable or observable result. A useful bullet might explain that you designed an API, reduced a repeated manual step, tested a component, or analysed a dataset. Do not claim team results as individual work, and be ready to demonstrate or discuss every item."),
            new("Use skills as a claim you can support", "Group skills into clear categories such as languages, frameworks, databases, design tools, or laboratory methods. Include a skill only when you can answer basic questions or show where you used it. Match accurate wording from the job description, but do not stuff hidden keywords or copy a long requirements list into the resume."),
            new("Check the document like an application", "Keep formatting consistent, use readable text, and export to PDF unless the employer asks for another format. Check links, dates, marks, spelling, phone number, and email address. Use a sensible file name such as Firstname-Lastname-Resume.pdf. Remove sensitive identifiers, full home addresses, and documents that were not requested.")
        ]),
        new("identify-fake-job-offers", "How to identify fake job offers and recruitment scams", "A verification checklist for suspicious recruiters, payment requests, copied brands, and unsafe application forms.", new(2026, 9, 30),
        [
            new("Treat urgency and guaranteed selection as warnings", "Legitimate hiring can move quickly, but a recruiter should not pressure you to pay immediately, hide the job description, or promise a guaranteed offer without assessment. Be cautious when the message focuses on easy income, asks you to recruit other people, or claims a senior role is available without checking your experience."),
            new("Verify through a separate channel", "Do not use only the phone number or link supplied in a suspicious message. Find the employer’s official website independently, locate its careers or fraud-warning page, and compare the vacancy, domain, and contact pattern. A logo, copied offer letter, social profile, or familiar display name is not proof. Email domains can be imitated with small spelling changes."),
            new("Never pay to secure a job", "Do not transfer money for an interview slot, offer letter, refundable security deposit, compulsory training, background verification, equipment shipment, or guaranteed placement. An authentic employer may describe legitimate examination fees in an official public notification, but the payee and payment page must match that authority. Never share passwords, PINs, or one-time passwords."),
            new("Limit and document what you share", "Provide only the information needed for the current application stage. Avoid sending full identity documents, bank details, or selfies with documents to unverified contacts. Save the message, email headers, number, URL, and payment request if you need to report an incident. Contact your bank immediately if money or credentials have already been exposed.")
        ]),
        new("prepare-walk-in-interview", "How to prepare for a walk-in interview", "Plan the verification, documents, travel, introduction, and follow-up for a walk-in hiring event.", new(2026, 9, 30),
        [
            new("Reconfirm the event before travelling", "Check the employer’s official source for the date, reporting window, venue, eligible profiles, registration method, and documents. Recheck on the day because walk-ins can be rescheduled or closed when capacity is reached. If the venue is a third-party office, confirm the relationship and never pay an individual to reserve a slot."),
            new("Carry a small, organised document set", "Bring the number of resume copies requested, identification, photographs, academic records, experience documents, and application confirmation only when relevant. Keep originals separate from photocopies and hand them over only for a clear verification purpose. Store digital backups securely rather than sharing an unrestricted cloud folder."),
            new("Prepare for a short first impression", "Walk-in screening is often brief. Practise a 45-second introduction covering your education or current role, relevant skills, one proof point, and why this position fits. Review the company, role, and likely basics. Dress appropriately for the workplace, arrive early, and remain professional with coordinators as well as interviewers."),
            new("Record the next step", "Before leaving, note the stage completed, the name or team that communicated with you, and the expected timeline. Use only official contact details for follow-up. A short message after the stated waiting period is enough. Continue other applications rather than treating an informal positive comment as a confirmed offer.")
        ]),
        new("prepare-aptitude-tests", "How to prepare for aptitude and online assessment tests", "A focused method for diagnostic practice, accuracy, time management, and test-day readiness.", new(2026, 9, 30),
        [
            new("Diagnose before practising at volume", "Take one timed sample that resembles the employer’s stated pattern. Record mistakes by topic and cause: concept gap, calculation error, misreading, or time pressure. This gives you a study order. Repeating random questions can feel productive while leaving the same weak areas untouched."),
            new("Build accuracy before speed", "Review the core methods for percentages, ratios, averages, profit and loss, time and work, probability, logical arrangements, data interpretation, and verbal reasoning as relevant. Solve slowly until the method is reliable, then use short timed sets. Keep an error log and redo missed questions without looking at the answer."),
            new("Use a deliberate test strategy", "Read the marking rules, section limits, navigation restrictions, and calculator policy before starting. Make a first pass through questions you can solve confidently, mark reasonable returns, and avoid spending several minutes protecting one answer. If there is negative marking, guessing should follow the stated scoring rather than emotion."),
            new("Prepare the environment", "For a remote proctored test, use the supported browser and device, test the camera and microphone, close unrelated applications, arrange power and internet backup, and keep the permitted identification nearby. Follow proctoring rules exactly. For an assessment centre, confirm travel, reporting time, stationery rules, and identification the previous day.")
        ]),
        new("apply-safely-company-career-portals", "How to apply safely on company career portals", "Verify the vacancy, protect your data, complete the application accurately, and preserve proof of submission.", new(2026, 9, 30),
        [
            new("Begin from a verified company path", "Open the company’s official domain yourself and find its careers section, or compare the application domain with links published there. Some employers legitimately use applicant-tracking providers, but the company’s own site should lead to that provider. Avoid shortened or misspelled links received only through unsolicited messages."),
            new("Match the exact vacancy", "Confirm the title, location, job identifier, qualifications, and closing date before creating an account. Read privacy notices and application questions. If a summary site and the employer page disagree, use the employer’s current posting as the authority. Do not apply to an unrelated role merely because the title looks similar."),
            new("Share data in stages", "Use a strong unique password for the portal and never send a one-time password to a recruiter. Upload only requested files. Bank details, tax identifiers, and extensive identity documents are rarely needed at the first application stage. If a later background check requests sensitive information, verify the employer and screening provider independently first."),
            new("Keep a reliable record", "Save the job identifier, submitted resume version, date, confirmation number, and a copy or screenshot of important answers. This helps you prepare if contacted and distinguish a genuine follow-up from a generic scam. Revisit the portal through your saved official link rather than clicking unexpected status messages.")
        ]),
        new("mechanical-career-options", "B.E. Mechanical career options for fresh graduates", "Compare design, manufacturing, quality, maintenance, operations, and technical sales roles before choosing an early-career path.", new(2026, 9, 30),
        [
            new("Understand the work behind each title", "Mechanical graduates may begin in product or CAD design, production planning, quality, maintenance, testing, project coordination, service, or technical sales. A title such as graduate engineer can describe very different work at two employers. Read the responsibilities and ask what a typical week looks like before judging a role by the company name alone."),
            new("Map coursework to practical evidence", "Select examples from design projects, workshops, laboratories, internships, and final-year work. Explain the requirement, your calculation or design choice, tools used, safety considerations, and result. For CAD roles, be ready to discuss drawings, tolerances, and revision control. For quality or production, connect measurement, process variation, and root-cause methods to a concrete example."),
            new("Check site and schedule conditions", "Manufacturing and service positions may include plant shifts, travel, customer sites, protective equipment, or work in a location far from a city centre. Confirm the worksite, transport, shift rotation, training period, and relocation expectations. These details affect whether the opportunity fits your circumstances and should be clear before accepting an offer."),
            new("Build depth one direction at a time", "Choose one or two relevant tools or topics to strengthen instead of listing every engineering software package. A design candidate might deepen drawing interpretation and one CAD tool; a production candidate might practise process mapping and basic data analysis. Keep your claims accurate and demonstrate how you learned the tool through a project or supervised task.")
        ]),
        new("btech-fresher-job-guide", "B.Tech fresher job search guide", "Organise a B.Tech job search around branch fit, batch rules, evidence, application quality, and a sustainable routine.", new(2026, 9, 30),
        [
            new("Separate broad eligibility from branch fit", "Some employers accept any engineering branch, while others specify a short list. Check the official wording for eligible degrees, branch names, graduation year, minimum marks, backlogs, and experience. Do not assume that a related-sounding degree is accepted; an application can be rejected automatically when a required field does not match."),
            new("Create proof for the roles you want", "Choose two or three target role families and prepare one clear project or internship example for each. Software roles benefit from demonstrable code and testing; core roles benefit from design, lab, or plant examples; analytics roles benefit from a careful data project. Explain your personal contribution and the limits of your result honestly."),
            new("Keep applications traceable", "Record company, job identifier, source link, role, location, batch eligibility, deadline, resume version, and application date. This makes it easier to spot repeat applications and prepare when a recruiter calls. Save an official confirmation when the portal provides one and check the employer site again before acting on a later message."),
            new("Use a weekly routine you can maintain", "Set time for finding verified openings, tailoring applications, learning a relevant skill, interview practice, and rest. A small number of thoughtful applications is easier to follow up on than a large batch of identical submissions. Review the routine each week based on response rates and the skills employers actually request.")
        ]),
        new("fresher-application-checklist", "Fresher job application checklist", "A repeatable checklist to confirm eligibility, prepare the right files, submit accurately, and track each application.", new(2026, 9, 30),
        [
            new("Before opening the application form", "Confirm the employer’s official vacancy, exact title, job code, location, closing date, qualification, graduation batch, experience, and application domain. Read the full notice and identify any marks, age, language, shift, or document conditions. If a key fact is unclear, pause and verify it with the employer’s published channel."),
            new("Prepare only the requested material", "Use a current, role-relevant resume and check the required file type and size. Keep academic records, project links, certificates, and identification ready where the employer requests them. Do not send bank credentials, passwords, one-time codes, or broad identity documents just because an informal contact asks for them."),
            new("Review before submitting", "Check every name, date, phone number, email, degree, and answer for consistency with your records. Read declarations carefully and correct mistakes before submission if the portal allows it. Make sure links work and that the file opens. Never invent experience, marks, tools, or project results to satisfy a form field."),
            new("Keep the confirmation and next step", "Record the submission date, role identifier, confirmation number, and resume version. Save the receipt or confirmation email. Note any test, interview, or document-verification deadline and the official contact route. A tracker prevents accidental repeat applications and helps you recognise messages that do not refer to the role you submitted.")
        ]),
        new("off-campus-hiring-guide", "How off-campus hiring usually works", "Understand common registration, screening, assessment, interview, and offer stages while checking each employer’s actual process.", new(2026, 9, 30),
        [
            new("Registration and eligibility screening", "A drive may begin with an employer portal form, a third-party assessment registration, or a college-independent sign-up page. Enter graduation and academic details exactly as requested. Some employers impose minimum marks, backlog limits, accepted branches, or restrictions on prior applications, and those rules can be used for automated screening."),
            new("Assessment and shortlisting", "The next stage may include aptitude, coding, domain knowledge, language, or situational judgement exercises. The format depends on the role, so use the notification rather than assuming every drive follows the same test. Read time limits and marking rules, practise the relevant fundamentals, and test the required device or travel plan in advance."),
            new("Interviews and document checks", "Interviews may combine technical discussion, project review, communication, and role fit. Prepare examples you can explain and bring only the documents requested through a verified process. If several employers are involved in a pooled event, confirm which company receives your data and how your application is shared."),
            new("Offers, deadlines, and decisions", "Read the written offer for role, location, compensation components, joining date, probation, training, and any service commitment. Ask for clarification through an official contact before accepting. Verbal assurances do not replace written terms, and a legitimate employer should not require payment to issue a job offer.")
        ]),
        new("avoid-recruitment-fee-scams", "Recruitment fees and job offer red flags", "Recognise payment pressure, fake selection claims, and unsafe requests before sharing money or personal information.", new(2026, 9, 30),
        [
            new("Pause when money is tied to selection", "A request to pay a recruiter, intermediary, or personal account to guarantee an interview, offer, joining date, or placement is a strong warning sign. Do not send a “refundable” deposit or buy required equipment from a link sent by an unverified contact. If an official examination has a fee, verify the amount and payee in the public authority’s own notification."),
            new("Check the sender and the vacancy separately", "Look at the full sender address, website spelling, job identifier, and independently published contact details. Ask the company through its official careers or support channel whether the recruiter and vacancy are real. Do not call only the number in a suspicious message, and do not rely on a forwarded PDF as proof."),
            new("Protect credentials and identity", "No recruiter needs your email password, bank PIN, card security code, or one-time password. Be cautious with requests for a selfie holding an identity document or full financial details before a verified hiring stage. Use a separate strong password for job portals and restrict public access to resume contact details where possible."),
            new("If you have already responded", "Stop sending money and information. Contact your bank or payment provider quickly if a transfer or card detail was exposed, change reused passwords, and secure your email account. Preserve messages, numbers, links, receipts, and timestamps. Report the incident to the relevant platform or authorities in your jurisdiction.")
        ]),
        new("remote-job-interview-prep", "Prepare for a remote job interview", "Set up the technology, space, examples, and communication habits that help a video interview run smoothly.", new(2026, 9, 30),
        [
            new("Check the meeting details", "Confirm the time zone, meeting link, expected duration, interviewer names, and platform. Install or update the software from its official source and test it ahead of time. If an invitation asks you to install an unknown file or share account credentials, verify the request with the employer using a separate channel."),
            new("Make the connection reliable", "Test camera, microphone, speakers, lighting, and internet in the room you will use. Plug in your device, close bandwidth-heavy applications, and keep a phone hotspot or dial-in option available if practical. Put the camera at eye level and choose a quiet background where you can focus on the conversation."),
            new("Structure concise examples", "Prepare a few examples of solving a problem, learning a tool, handling a setback, and collaborating with others. Explain context, your action, and the result in plain language. For technical interviews, ask clarifying questions, describe your reasoning, and test your solution rather than racing silently to an answer."),
            new("Close with clarity", "Keep the role description and a short list of questions nearby. Ask about team work, first-month expectations, training, and next stages when relevant. Thank the interviewer, note what was discussed, and follow the stated timeline. Send a brief follow-up only through a verified contact route if appropriate.")
        ]),
        new("compare-entry-level-offers", "How to compare entry-level job offers", "Compare the full role, compensation, location, schedule, training, and written terms before making a decision.", new(2026, 9, 30),
        [
            new("Compare total compensation carefully", "Separate fixed pay from variable incentives, joining bonuses, reimbursements, and benefits. Ask which amounts are guaranteed, how often incentives are paid, and what deductions apply. A headline package is difficult to compare without the written salary structure, expected work hours, and employment type."),
            new("Evaluate the work and learning", "Clarify the day-to-day responsibilities, manager or team, training plan, tools, and how performance is reviewed. A role can be a good start when it builds skills you want, even if its title is broad. Ask for concrete expectations rather than relying on promises of rapid promotion or future conversion."),
            new("Include location and schedule costs", "Consider commute or relocation, shift timing, travel, remote-work expectations, equipment, and family or study commitments. Calculate realistic take-home pay after living and travel costs. Ask whether location or shift can change and how much notice the employer normally gives."),
            new("Read conditions before signing", "Review probation, notice, training recovery clauses, service commitments, confidentiality terms, start date, and conditions that could change the offer. Request clarification in writing. Compare only written terms from a verified employer and never pay a person to release an offer or reserve a position.")
        ]),
        new("government-job-notification-checklist", "Government job notification checklist", "A careful way to read official recruitment notices, identify deadlines, and keep a complete application record.", new(2026, 9, 30),
        [
            new("Identify the authoritative notice", "Confirm the issuing department or public body, advertisement number, publication date, official web domain, and any corrigendum or later update. Search snippets and copied summaries can omit changes. Use the notice and the authority’s recruitment portal as the source of truth for current information."),
            new("Check personal eligibility line by line", "Compare the accepted degree, subject, age on the stated cutoff date, category rules, experience, nationality, language, physical or medical standards, and permitted attempt limits. Keep evidence for each condition. Where a rule is ambiguous, use the authority’s published clarification channel instead of assuming the most favourable interpretation."),
            new("Build a date and document plan", "Write down registration opening and closing dates, fee deadlines, correction windows, examination dates, and required document formats. Prepare certificates early and verify names and dates across records. Use only the official payment method and save the transaction receipt and final application copy."),
            new("Follow updates through official channels", "Check the recruitment portal for admit cards, schedule changes, answer keys, and results. Do not pay someone who claims special access to a selection list. Preserve application credentials securely and avoid public posts that expose roll numbers, personal identity details, or login codes.")
        ]),
        new("first-job-document-preparation", "Documents to prepare for your first job", "Organise common education and application records while sharing sensitive documents only when a verified employer requests them.", new(2026, 9, 30),
        [
            new("Keep a private, organised record", "Maintain clear copies of your resume, degree or provisional certificate, semester marksheets, relevant project evidence, and experience or internship letters if you have them. Use descriptive file names and a secure storage location with account protection. Keep original documents safe and do not leave them with an interviewer."),
            new("Follow the employer’s requested list", "Requirements vary by role and stage. Some applications need only a resume; later verification may request education or identity records. Read the exact instructions, file types, size limits, and deadline. Do not upload every personal document into a general form just because the field is optional."),
            new("Check consistency and legibility", "Compare your spelling, degree title, dates, marks, and contact details across the application and documents. Scan pages flat, include all sides only when asked, and confirm that the file opens before uploading. If your records contain a discrepancy, ask the issuing institution how it can be corrected rather than editing the document yourself."),
            new("Limit exposure of sensitive information", "Share identity numbers, tax details, bank information, or photographs only through a verified employer process when required. Confirm the domain and privacy purpose first. Never send passwords, PINs, or one-time passwords, and do not hand over originals as security for an interview or offer.")
        ])
    ];

    public static CareerResource? Find(string slug) => All.FirstOrDefault(article => article.Slug.Equals(slug, StringComparison.OrdinalIgnoreCase));
}
