namespace JobForFresher.Models;

public sealed record CategoryPreparationSection(string Heading, string Body);
public sealed record CategoryPreparationGuide(string Category, IReadOnlyList<CategoryPreparationSection> Sections)
{
    public string Heading => CategoryGuides.For(Category)!.Heading;
    public string Introduction => CategoryGuides.For(Category)!.Introduction;
    public string Anchor => "guide-" + JobCategories.Slug(Category);
    public DateOnly Updated => new(2026, 9, 30);
}

public static class CategoryPreparationGuides
{
    private static readonly IReadOnlyDictionary<string, CategoryPreparationGuide> Content = new CategoryPreparationGuide[]
    {
        new("Freshers Jobs",
        [
            new("Understand the opportunity", "Compare the employer's stated qualification, graduation batch, location and experience requirements with your circumstances. Note what is essential and what is described as desirable. Check whether the position is employment, an apprenticeship or an internship, and ask about supervision and the initial learning period. If training terms, working hours or compensation are unclear, write down questions for the recruiter. Keep the vacancy link and job identifier in your application tracker so you can revisit the original information when an interview invitation arrives. Choose roles you can explain a genuine interest in."),
            new("Build a truthful application", "Use a clear resume that explains your education, relevant skills and practical work. For a college project, state the problem, your contribution, the tools you used and what you learned from testing it. A small completed project can support a stronger conversation than a long list of tools you cannot explain. Check contact details, dates and links before submitting. Give files sensible names and follow the requested format. Keep a copy of the resume you sent so your interview answers match the application. Describe achievements accurately without inventing results or experience."),
            new("Prepare for the interview", "Practise a short introduction covering your education, one relevant project and why the role interests you. Prepare examples of learning something difficult, working with others and correcting a mistake. Structure each example around the situation, your action and the result, including what you would improve. Revise the fundamentals mentioned in the vacancy and explain them aloud in simple language. Ask a friend to challenge your project claims with follow-up questions. Practise listening to the complete question before deciding which example best answers it. Review difficult questions after every practice session."),
            new("Behave professionally on the day", "Arrive or connect a little before the agreed time, follow the venue instructions and keep your phone silent. Choose clean, comfortable clothing appropriate to the setting. Greet the interviewers politely and listen without interrupting. It is acceptable to pause, ask for clarification or say that you have not encountered a topic yet. Explain how you would approach learning it rather than guessing confidently. Speak respectfully about classmates and previous teams, share credit for group work and describe your own responsibilities without exaggeration. Keep your answers focused and allow time for questions."),
            new("Ask questions and follow through", "Ask what a new joiner is expected to learn, how feedback is provided and what a typical first month involves. Clarify the next stage and the expected communication channel before leaving. If follow-up is invited, send one concise message after the stated timeline rather than repeatedly contacting several employees. Record the questions you found difficult and revise those areas for your next interview. Read any written offer carefully, confirm unclear terms through the employer's official contact and make your decision using the complete information. Continue developing skills while awaiting a response.")
        ]),
        new("Off Campus",
        [
            new("Check the drive details", "Read the official announcement before registering. Confirm the eligible branches, graduation years, academic conditions, work location and registration deadline. Look for instructions about previous applications, assessment invitations and documents. Save the exact vacancy link and any confirmation number rather than relying only on a forwarded message. If an important condition is ambiguous, use the employer's published contact channel to clarify it. Keep a calendar for registration, assessment and interview dates, with time to prepare the requested material. Treat each drive separately because another employer's selection process may be different."),
            new("Make registration reliable", "Enter your name, education and contact information consistently with your records. Review marks and dates carefully, and do not round or reinterpret values unless the form tells you how. Upload the requested resume version and open the file once to confirm it works. Use an email address you check regularly and watch the spam folder for an expected invitation. Record what you submitted and when. If a portal fails, retain the error details and contact the stated support channel without creating duplicate registrations unnecessarily. Review the instructions again before attempting another submission."),
            new("Prepare for assessments and interviews", "Build your revision plan around the subjects and stages actually named in the announcement. When aptitude or coding is included, practise under a time limit and review why you made mistakes. For technical discussions, prepare a project walkthrough covering the problem, approach, testing and your individual contribution. Rehearse an introduction and examples of teamwork and learning. If the assessment is online, check the device, browser and identification instructions beforehand. Use only the materials and assistance permitted by the assessment rules. Plan enough rest so you can concentrate during the scheduled session."),
            new("Show responsible interview behaviour", "Join the correct session on time and use the name given in your application. Listen carefully to announcements, especially when several candidates are being assessed together. In a group discussion, contribute a relevant point, invite others to speak and respond to ideas respectfully. Avoid dominating the conversation or repeating someone else's point as your own. During an individual interview, explain your reasoning and acknowledge uncertainty. If a technical problem interrupts a remote session, report it through the designated channel calmly and follow the recovery instructions. Keep other candidates' personal information private."),
            new("Manage results and next steps", "Ask where results will be communicated and whether further action is required from you. Keep assessment and interview messages together so you can distinguish an authentic follow-up from an unrelated approach. If you are not selected, record the areas that need work without assuming you know the employer's reasons. Continue applying to suitable roles while improving those skills. If you receive an offer, clarify the role, location, joining date and training arrangements in writing before making commitments based on an informal conversation or forwarded screenshot. Maintain an accurate record of every application.")
        ]),
        new("Walk-in",
        [
            new("Verify the event before travelling", "Check the date, reporting window, full address, role and eligibility against the employer's published announcement. Confirm whether advance registration or an invitation is required even though the event is described as a walk-in. Plan the journey and allow for delays without arriving outside the stated access hours. Recheck the notice before leaving for venue or schedule updates. If you need an accessibility arrangement, contact the organizer through the published channel to understand available support. Save the official event details where you can find them easily during the journey."),
            new("Pack a useful interview folder", "Carry the documents requested in the announcement and organize copies so you can find them quickly. Keep your resume, invitation or registration details and relevant project information together. Follow the employer's instructions about identification and original documents; do not leave originals with an unofficial intermediary. Bring a pen and note the recruiter contact provided for the event. Keep digital copies accessible where appropriate, but avoid sharing sensitive documents in public groups. Prepare water and essential personal items if you expect a long day. Check your folder before leaving home."),
            new("Rehearse for a short conversation", "Practise a concise introduction that names your background, relevant skill and reason for attending this particular role. Prepare two examples you can explain quickly, such as resolving a project problem or handling a team disagreement. Review the responsibilities and practise skills directly related to them: a support role might involve a customer scenario, while an engineering role may involve technical questions. Prepare a longer explanation if invited, but begin with the point that answers the question. Keep your examples factual and specific. Avoid claiming expertise you cannot demonstrate when asked."),
            new("Be considerate at the venue", "Follow security and registration instructions, wait in the designated area and treat coordinators and other candidates respectfully. Keep your phone quiet and avoid discussing another candidate's personal information or interview answers. When called, greet the interviewer, listen carefully and answer at a measured pace. If you are unsure about a question, ask for clarification instead of rushing. Explain any availability or shift limitations honestly. Long queues can be frustrating, but calm communication helps you obtain useful information without making the situation harder for others. Keep track of your documents and belongings."),
            new("Leave with clear next steps", "Before leaving, ask how shortlisted candidates will be contacted and whether you need to complete another form or assessment. Check that you have all your belongings and documents. After the event, record the role, recruiter channel, questions asked and any promised timeline. Follow up through the stated contact if appropriate after that timeline passes. Do not treat an informal positive comment as a written offer. Compare the eventual responsibilities, work location, schedule and compensation with your needs before accepting a position or planning relocation. Use the experience to improve your next interview.")
        ]),
        new("IT Jobs",
        [
            new("Identify the skills that matter", "Separate the vacancy's core requirements from optional tools and broader descriptions. Note the expected programming language, operating environment, data skills and collaboration practices. Check whether the role involves shifts, customer support or on-call responsibilities and ask how those arrangements work. Choose a few relevant fundamentals to revise in depth instead of collecting unfamiliar terms. Match each important requirement to an example from a project, lab or internship. Where you have a gap, describe what you have already tried and what you still need to learn. Build your preparation around the actual responsibilities."),
            new("Prepare a project walkthrough", "Select a project you can explain from the user's problem through implementation and testing. Be ready to describe the main components, how data moves and what happens when something fails. Explain one decision you made, an alternative you considered and a bug you investigated. Make sure any demonstration runs and repository links open. Remove credentials and private information before sharing code. For group projects, identify your contribution clearly and credit others. Honest limitations often lead to a more useful discussion than inflated performance claims. Prepare a brief explanation before showing implementation details."),
            new("Practise technical interviews", "When a coding exercise is relevant, practise clarifying inputs, outputs and constraints before writing a solution. Explain a simple approach first, then discuss improvements if time permits. Test normal cases, empty inputs and boundary conditions, and describe the trade-offs in your chosen structure. For testing or support roles, practise turning a vague failure report into reproducible steps and useful evidence. Review your mistakes after each practice session. During the assessment, follow the stated rules about documentation, external tools and assistance instead of assuming they are permitted. Ask when those rules are unclear."),
            new("Communicate with professionalism", "Think aloud enough to make your reasoning understandable, but give the interviewer room to ask questions. If feedback points out an error, examine it calmly and correct your approach. Say when you are making an assumption or when you do not know a detail. Avoid dismissing a tool, team or previous implementation without understanding its constraints. In a remote interview, test screen sharing and close private windows before the call. Keep explanations focused on the question and check whether the interviewer would like more technical depth. Listen carefully before defending a decision."),
            new("Ask about the working environment", "Ask how new engineers are supported, how changes are reviewed and how the team tests work before release. Find out what success looks like during the first few months and which systems you would learn first. Clarify the balance between feature work, maintenance and support. After the interview, note topics that exposed gaps and build a small exercise to practise them. If an offer follows, confirm the actual role and working arrangement rather than assuming the title guarantees a particular technology stack or career path. Keep your learning plan focused and realistic.")
        ]),
        new("Government Jobs",
        [
            new("Create a notice checklist", "Record the advertisement number, post name, application dates and official portal. Read the qualification and experience conditions, including any specified reference dates. Where relevant, check the authority's instructions about age, categories, certificates and fees directly in the notice. Do not assume a concession or certificate format from an earlier recruitment still applies. Mark any condition you cannot interpret and seek clarification through the published help channel. Keep the notice and subsequent amendments together, and review updates before each important stage. This guide helps organize preparation; the current notification determines the requirements."),
            new("Submit carefully and keep records", "Prepare files in the size and format requested by the portal, and check that scanned text is readable. Enter personal and academic information consistently with your supporting records. Review the complete form before submission and retain the acknowledgement. If a fee applies, use the payment route identified by the recruiting authority and save the receipt. Check correction-window instructions instead of assuming every field can be changed later. Protect application credentials and avoid sending documents or payment details to unofficial contacts offering preferential access. Keep copies organized by advertisement and post number."),
            new("Study for the announced stages", "Use the published syllabus and assessment scheme to divide preparation into manageable topics. If an examination is part of recruitment, practise relevant questions under timed conditions and review errors by topic. If an interview is included, prepare to explain your education, practical experience and motivation for the post. Understand the responsibilities described in the notice and relate your examples to them. Keep factual and opinion-based answers distinct. Revise steadily and allow time for document preparation rather than leaving administrative tasks until the assessment date. Review progress regularly and adjust your study priorities."),
            new("Behave respectfully during assessment", "Follow the reporting, identification and permitted-item instructions for the centre. Treat staff and other candidates courteously, and ask procedural questions through the designated channel. In an interview, listen to the complete question, pause briefly and give a direct answer supported by an example where appropriate. If you do not know a fact, acknowledge that instead of inventing an answer. Discuss public-service situations with fairness and respect for the people involved. Avoid claiming access to officials or influence over selection as part of your presentation. Keep your answers relevant and your tone measured."),
            new("Track official outcomes", "Use the recruiting authority's published channels to check results, document-verification instructions and further dates. Read each notice carefully because qualifying for one stage may require action before the next. Keep submitted forms, receipts and relevant certificates organized so you can respond promptly. If information appears inconsistent, use the official clarification process rather than relying on social messages. Continue preparation while waiting, but do not describe yourself as appointed until the authority issues the applicable formal communication. Confirm joining instructions before making travel or relocation commitments. Retain important communications for your own records.")
        ]),
        new("Bank Jobs",
        [
            new("Understand the post and process", "Check the employer, post identifier, qualification and experience requirements using the official vacancy. Note the work location, transfer expectations and any required language or specialist skills. Distinguish a customer-facing sales position from an operations or technical role before deciding what to revise. Where recruitment includes examinations, use the published pattern and syllabus. Where it involves direct interviews, concentrate on the stated responsibilities. Write down unclear terms about targets, working arrangements or training so you can ask precise questions. Do not assume that every banking vacancy uses the same selection process."),
            new("Prepare relevant examples", "Choose examples that show accuracy, confidentiality, teamwork and clear explanation. You might discuss how you checked inconsistent figures in a college project, organized records or explained a difficult topic to someone unfamiliar with it. Describe your action and result without claiming banking experience you do not have. For a specialist position, connect your technical work to the requirements stated in the vacancy. Review your resume because an interviewer may ask how you used a listed tool or what you learned from an assignment. Practise answering those questions with specific, truthful details."),
            new("Practise the announced assessments", "If reasoning, numerical skills or language are part of selection, practise those sections with the stated time limits in mind. Analyse mistakes before increasing the number of questions. For an interview, prepare a concise explanation of why the particular role interests you. Read the employer's own description of its services and think about the customers the role supports. Practise scenarios by clarifying the facts, identifying what you can do and explaining when you would seek guidance instead of inventing a procedure. Use preparation materials that match the announced scope of assessment."),
            new("Show calm and responsible behaviour", "Listen patiently, answer the question asked and use clear language without unnecessary jargon. In a customer scenario, acknowledge the concern before describing the next step. Do not promise an outcome you cannot authorize or suggest bypassing checks to satisfy a customer. Explain that you would follow the employer's process and consult the appropriate colleague when needed. Treat hypothetical customers respectfully regardless of their background or knowledge. During the interview, keep your phone silent, avoid interrupting and correct a mistaken statement openly if you notice it. Show care when discussing sensitive information."),
            new("Clarify expectations and follow up", "Ask about training, supervision, typical responsibilities and how a new joiner's progress is assessed. For customer-facing roles, clarify the balance between service, operations and sales rather than relying on the title alone. Confirm the next recruitment stage and use the stated communication channel for follow-up. Review a written offer for the actual role, location and compensation structure, and ask the employer to explain unclear terms. Keep improving the skills highlighted by the interview while waiting, without treating an informal assurance as a confirmed appointment. Keep application records so you can respond accurately.")
        ]),
        new("Internship Programs",
        [
            new("Check whether the placement fits", "Confirm the duration, expected hours, location, work arrangement and academic eligibility. Ask about the stipend or expenses if the announcement is unclear. Check whether your college requires approval or a particular schedule before promising availability. Look for a named team, defined responsibilities and a way to obtain feedback. If the role mentions possible conversion to employment, ask how that decision is made rather than assuming it is guaranteed. Compare the opportunity with the skills and experience you want to develop. Choose learning goals that are realistic for the advertised internship period."),
            new("Present a relevant portfolio", "Choose coursework, a personal project, volunteering or a practical exercise related to the internship. Explain the problem, what you did and how you evaluated the result. A short, clear example is more useful than a collection of unexplained links. Check that files open and that a portfolio can be viewed without unnecessary access requests. For group work, describe your contribution accurately. If you are still learning a tool, say what you have used it for and what you would need help with. Be ready to explain a challenge and how you approached it."),
            new("Prepare for discussion and tasks", "Review the fundamentals named in the advertisement and practise explaining your work to someone outside your class. Prepare examples of receiving feedback, meeting a deadline and asking for help productively. If the employer requests an assignment, read its scope, deadline and permitted resources carefully. Ask questions when the deliverable is ambiguous, and state assumptions in your submission. Keep your work honest and explainable. Rehearse a brief introduction connecting your interests to the team's work without suggesting you already understand every part of the role. Review your submission before the interview."),
            new("Demonstrate good working behaviour", "Be punctual, listen closely and take useful notes without interrupting. When you do not understand something, explain what you understood first and then ask a focused question. Show that you can accept feedback by describing how you would revise your approach. Be honest about exams, classes and other commitments affecting attendance. Avoid promising an unrealistic workload just to impress the interviewer. If you discuss previous teams, give credit fairly and focus on what you learned rather than criticizing people or sharing confidential information. Ask for clarification when expectations appear to conflict."),
            new("Turn the opportunity into learning", "Ask who would supervise you, what an early task might look like and how often you could expect feedback. Clarify what you may share publicly before adding work to a portfolio. If selected, agree on realistic goals and track progress with notes about tasks, feedback and improvements. Raise blockers early and offer a proposed next step where possible. At the end, summarize your contribution and learning accurately. Any certificate, reference or future role should be discussed as an explicit arrangement rather than assumed. Keep building skills beyond the tasks you already know.")
        ]),
        new("Work From Home Jobs",
        [
            new("Verify the remote arrangement", "Check the vacancy on the employer's published careers channel and confirm the application route. Read whether the role is fully remote, hybrid or temporarily home based. Ask about eligible locations, time zones, working hours, office visits and employment type when unclear. Clarify equipment, connectivity and support arrangements before making purchases. Treat requests from informal contacts for passwords, payment to secure a job or access to your device with caution. Use independently verified employer contact details to resolve doubts about an invitation. A remote label alone does not explain the working conditions."),
            new("Prepare your interview setup", "Test the meeting application, microphone, camera and internet connection before the scheduled time. Choose a space where you can hear clearly and limit interruptions, and tell others when you need quiet. Keep the invitation and recruiter contact accessible in case the connection fails. Use a professional display name and close unrelated windows before sharing your screen. You do not need an elaborate background; prioritize clear sound and a workable connection. If you need an accommodation or alternative format, discuss it with the recruiter in advance. Have your resume available for reference."),
            new("Show evidence of independent work", "Prepare an example of planning a task, breaking it into steps and checking progress without constant supervision. Explain how you handled a blocker and when you asked for help. For a technical role, show how you recorded a problem so another person could reproduce it. For an operational role, describe how you kept records accurate and priorities visible. Practise writing a brief update stating what is complete, what remains and what decision you need. Adapt examples to the responsibilities advertised. Explain how you would communicate a delay early enough for others to respond."),
            new("Behave thoughtfully on calls", "Join on time, greet the interviewer and check that you can hear each other. Allow a short pause before responding if the connection has a delay. Listen without multitasking and explain if you need a moment to locate a document. If audio fails, state the problem calmly through the available channel instead of repeatedly speaking over the other person. Avoid showing private messages or documents during screen sharing. Be honest about availability and working conditions, and ask how the team handles urgent requests outside normal hours. Keep your answers clear and focused."),
            new("Clarify how the team works", "Ask how tasks are assigned, how progress is reviewed and which communication channels serve different needs. Discuss onboarding, training and access to help for new joiners. Clarify whether performance is assessed through agreed outcomes, scheduled coverage or another approach. If selected, establish a routine for focused work, breaks and updates that fits the agreed schedule. Keep work information in approved systems and follow the employer's access instructions. Review written terms before assuming flexibility means working from any location at any time. Agree on how you will notify the team about unexpected interruptions.")
        ]),
        new("Core Engineering Jobs",
        [
            new("Understand the engineering context", "Check the accepted branches, qualification level, experience and location in the vacancy. Read whether the position is a graduate role, apprenticeship, trainee appointment or experienced hire. Note any stated software, drawing, measurement or documentation skills. Clarify shifts, travel and site arrangements instead of assuming all engineering work happens in an office. If the notice specifies additional conditions, verify them directly with the employer. List the main tasks and connect each to a subject or practical exercise you can discuss confidently. Choose examples that reflect the discipline and work environment of this role."),
            new("Revise through practical examples", "Select a laboratory exercise or project illustrating a relevant principle. Explain the objective, assumptions, method and observations before describing the conclusion. Be prepared to discuss units, measurement limits and why a result might differ from an expected value. Review relevant diagrams, calculations or drawings you have used. If software was involved, explain the inputs and how you checked the output rather than treating the tool as proof of correctness. Acknowledge where a classroom exercise differs from a real production or site environment. Keep project evidence organized so you can explain it clearly."),
            new("Prepare for technical questions", "Practise breaking an unfamiliar problem into known facts, missing information and a possible first step. Explain why you would choose a calculation, inspection or test before proposing a change. For maintenance scenarios, focus on gathering evidence and following authorized procedures rather than guessing at a repair. For design work, discuss constraints and how you would compare alternatives. Keep examples within your experience and say when you would consult a qualified supervisor. Prepare to explain a failed experiment and what it taught you about checking assumptions. Listen for additional conditions before finalizing an answer."),
            new("Show professional and careful behaviour", "Follow the venue's access and safety instructions, especially if the interview includes a workshop or site visit. Do not touch equipment or demonstrate an operation without authorization. In discussion, listen carefully, use clear terminology and ask for clarification when a diagram or condition is incomplete. Treat technicians, operators and other team members respectfully; practical knowledge may come from many roles. Explain mistakes honestly and avoid overstating your responsibility for group work. If you lack hands-on experience, show how you would learn under supervision rather than pretending otherwise. Recognize the limits of your knowledge."),
            new("Ask about supervision and development", "Ask what a new engineer would work on first, who reviews decisions and what training precedes independent tasks. Clarify the balance between desk work, shop-floor activity and travel. Discuss how the team records changes, checks quality and shares lessons from problems. After the interview, review the fundamentals you struggled to explain and practise with a worked example. If an offer follows, confirm the role, site, schedule and training arrangements in writing so expectations match the work you would undertake. Keep a realistic learning plan for the skills you need to strengthen.")
        ]),
        new("BPO / Support Jobs",
        [
            new("Understand the process and schedule", "Check whether the role is voice or non-voice, customer service or sales, and technical or general support. Review language requirements and be honest about your fluency. Clarify the location, shift pattern, transport arrangements and training period when relevant. Ask how fixed pay and any variable component are described rather than relying on a headline amount. Identify the tools or typing skills mentioned in the vacancy. Use this information to decide whether the work matches your strengths and availability. Preparation should reflect the advertised channel rather than a generic customer-service script."),
            new("Practise clear communication", "Prepare a brief introduction in the language required for the role. Speak at a steady pace and use simple words that make your message easy to follow. For email or chat, practise writing a response that acknowledges the issue, asks one useful question and explains the next step. Proofread names, dates and instructions before sending. For voice work, practise listening to a short scenario and summarizing it accurately. Avoid putting on an unfamiliar accent or using elaborate phrases that obscure your meaning. Ask a practice partner whether your explanation was easy to understand."),
            new("Work through customer scenarios", "Ask a friend to describe a problem with incomplete information, then practise clarifying it without making the person repeat everything. Confirm what you understand before suggesting an action. Explain what you would check, what you can do yourself and when you would escalate through the team's process. If you do not know an answer, say you would verify it rather than inventing a promise. Prepare an example of handling feedback or resolving a misunderstanding. Connect it to patience, accuracy and follow-through instead of claiming you never make mistakes. Keep the customer's objective in mind."),
            new("Behave calmly during the interview", "Greet the interviewer politely, listen without interrupting and answer directly. In a role-play, acknowledge frustration without blaming the customer or another colleague. Avoid arguing, making personal remarks or promising an outcome beyond your authority. If the interviewer changes the scenario, adapt your response instead of forcing a memorized script. Keep a professional tone when challenged and ask for clarification if needed. Be candid about shift availability and language skills so a successful interview leads to a role you can realistically perform. Pause briefly when necessary rather than filling every silence with an answer."),
            new("Ask about support and growth", "Ask how training works, where new staff find accurate information and who helps with unfamiliar cases. Clarify how quality, response time and customer outcomes are assessed for the advertised process. Find out how difficult interactions are escalated and how feedback is delivered. After the interview, practise areas where you hesitated, such as listening, typing or explaining steps. If selected, review the written role and schedule before accepting. Continue building product knowledge and communication skills rather than relying only on scripts. Use feedback to improve accuracy as well as the speed of your responses.")
        ])
    }.ToDictionary(guide => guide.Category, StringComparer.OrdinalIgnoreCase);

    public static CategoryPreparationGuide? For(string? category)
    {
        var name = category?.Trim();
        if (name == null) return null;
        if (Content.TryGetValue(name, out var guide)) return guide;
        var canonical = name.ToLowerInvariant() switch
        {
            "freshers" or "fresher" => "Freshers Jobs",
            "off campus drive" or "off-campus" => "Off Campus",
            "walk-in drive" or "walk in" => "Walk-in",
            "it/software" or "it / software" or "it" => "IT Jobs",
            "government/psu" or "government / psu" or "government" => "Government Jobs",
            "bank" or "banking" => "Bank Jobs",
            "internship" or "internships" => "Internship Programs",
            "wfh jobs" or "remote" or "work from home" => "Work From Home Jobs",
            "mechanical/core" or "mechanical / core" or "core engineering" => "Core Engineering Jobs",
            "bpo" or "support" or "bpo/support" => "BPO / Support Jobs",
            _ => null
        };
        return canonical != null ? Content[canonical] : null;
    }

    public static CategoryPreparationGuide ForJob(Job job) => For(job.Category) ?? For(job.SubCategory) ??
        (job.JobType.Contains("remote", StringComparison.OrdinalIgnoreCase) ? For("Work From Home Jobs") : null) ?? Content["Freshers Jobs"];
}
