namespace JobForFresher.Models;

public sealed record CategoryGuide(string Heading, string Introduction, string WhatToCheck, string PreparationTip);

public static class CategoryGuides
{
    private static readonly IReadOnlyDictionary<string, CategoryGuide> Content =
        new Dictionary<string, CategoryGuide>(StringComparer.OrdinalIgnoreCase)
        {
            ["Freshers Jobs"] = new("How to assess a fresher opening", "Fresher roles are designed for candidates at the beginning of their careers, but the meaning of “fresher” varies by employer. Some accept only the current graduating batch, while others consider applicants with up to one or two years of experience.", "Check the eligible degree, graduation years, location, training or probation terms, any service agreement, and whether the application is on the employer’s own careers site.", "Prepare two or three project examples that show what you built, how you solved a problem, and what you personally contributed."),
            ["Off Campus"] = new("Using off-campus drives effectively", "Off-campus recruitment lets employers assess students and graduates outside a single college placement process. A drive may have registration, assessment, interview, and document-verification stages on different dates.", "Confirm the eligible branches and batches, registration deadline, assessment location or platform, previous-application restrictions, and the exact communication channel the employer will use.", "Keep your resume, academic marks, government ID, and application confirmation ready, and revise aptitude plus the core subjects named in the notification."),
            ["Walk-in"] = new("Before attending a walk-in interview", "Walk-in hiring can move quickly, so the venue and reporting window matter as much as the job requirements. Employers may stop registrations when capacity is reached even if the advertised time has not ended.", "Verify the date, reporting time, complete address, contact instructions, required experience, and documents. Recheck the official source on the morning of the event for venue changes.", "Carry only requested documents, arrive early, prepare a concise introduction, and never pay an individual to reserve an interview slot."),
            ["IT Jobs"] = new("Choosing an early-career technology role", "Technology job titles often hide very different day-to-day work. Read the responsibilities to distinguish software development, testing, support, data, cloud, cybersecurity, and operations roles before deciding whether your projects match.", "Compare the required languages and tools with your real experience, note shift or support expectations, and check whether the role is office-based, hybrid, or fully remote.", "Revise fundamentals, be ready to explain your code and design decisions, and use a small working project or public repository as evidence of your skills."),
            ["Government Jobs"] = new("Read the official recruitment notice first", "Government recruitment is governed by the official notification. Summaries help with discovery, but eligibility, reservations, fees, age relaxation, examination stages, and document formats must be confirmed in the issuing authority’s notice.", "Check the advertisement number, application dates, age calculation date, category rules, syllabus, fee, correction window, and official portal before submitting anything.", "Create a deadline checklist, scan documents in the specified format, save payment and application receipts, and rely only on the authority’s published updates."),
            ["Bank Jobs"] = new("Plan for bank recruitment stages", "Bank hiring may include preliminary and main examinations, interviews, language requirements, background checks, or role-specific certifications. The process and eligibility differ between public-sector, private, cooperative, and specialist roles.", "Verify the recruiting organization, post code, degree and age requirements, location or transfer conditions, examination pattern, and whether experience is mandatory.", "Build a study plan around the official syllabus and practise timed reasoning, quantitative aptitude, English, and banking-awareness questions where those sections apply."),
            ["Internship Programs"] = new("Find an internship that builds evidence", "A useful internship should give you defined work, supervision, feedback, and an outcome you can explain later. The brand name alone matters less than what you will learn and produce.", "Check the duration, work location, hours, stipend, academic eligibility, conversion claims, ownership of work, and whether the application asks for an assignment or portfolio.", "Choose examples that demonstrate curiosity and follow-through. State your availability honestly and ask what a successful intern is expected to deliver."),
            ["Work From Home Jobs"] = new("Evaluate a remote job safely", "A genuine remote role should still identify the employer, responsibilities, working arrangement, and application process. Vague work-from-home offers that focus on easy income or request payment deserve extra caution.", "Confirm eligible work locations, time-zone or shift expectations, equipment and internet requirements, communication tools, employment type, and whether any office visits are required.", "Prepare a quiet interview space, test your connection and audio, and show how you organize work, communicate progress, and solve problems independently."),
            ["Core Engineering Jobs"] = new("Match the role to your engineering branch", "Core engineering openings can be highly specific about discipline, plant or site location, safety requirements, software, and practical exposure. A broad degree title does not automatically match every role.", "Review the accepted branches, technical subjects, shift or travel requirements, site conditions, apprenticeship status, medical standards, and any licence or software requirement.", "Revise the fundamentals most relevant to the job and prepare examples from labs, design projects, industrial visits, internships, or hands-on maintenance work."),
            ["BPO / Support Jobs"] = new("Understand the support role before applying", "Support and BPO roles vary across voice, non-voice, technical support, customer success, operations, and sales. The process, targets, shifts, and communication expectations can be very different.", "Check whether the role is voice or non-voice, domestic or international, technical or sales-focused, and note shift timing, transport, work location, language, and incentive terms.", "Practise a clear introduction, active listening, basic troubleshooting, and a calm response to a difficult customer scenario without memorising unnatural scripts.")
        };

    public static CategoryGuide? For(string? category) => category != null && Content.TryGetValue(category, out var guide) ? guide : null;
}
